export const REQUEST_TRIVIA_QUESTIONS = 'REQUEST_TRIVIA_QUESTIONS';

export const QUESTIONS_REQUEST_SUCESS = 'QUESTIONS_REQUEST_SUCESS';

export const QUESTIONS_REQUEST_FAILURE = 'QUESTIONS_REQUEST_FAILURE';

export const SET_USER_LOGIN = 'SET_USER_LOGIN';

export const CORRECT_ANSWER = 'CORRECT_ANSWER';

export const WRONG_ANSWER = 'WRONG_ANSWER';

export const RESET_GAME = 'RESET_GAME';

export const TIME_OUT = 'TIME_OUT';

export const NEXT_QUESTION = 'const NEXT_QUESTION';

export const SET_TIMER = 'SET_TIMER';

export const RESET_TIMER = 'RESET_TIMER';
