export const REQUEST_TRIVIA_QUESTIONS = 'REQUEST_TRIVIA_QUESTIONS';

export const QUESTIONS_REQUEST_SUCESS = 'QUESTIONS_REQUEST_SUCESS';

export const QUESTIONS_REQUEST_FAILURE = 'QUESTIONS_REQUEST_FAILURE';
